### ISSUE TITLE
Border-width + Hover causes issues with Padding inside a <div> causing it to "move"

### ISSUE THREAD

**Issue by bringacupcake** [SuperSimpleDev/html-css-course-2022#1]
<div>
      <button class="apply-button">Apply on Company Website</button>
      <button class="save-button">Save</button>
</div>

.apply-button {
  background-color: rgb(12, 91, 196);
  color: white;
  border: none;
  cursor: pointer;
  font-weight: bold;
  font-size: 16px;
  border-radius: 25px;
  padding: 16px 60px;
  margin: 10px 2px;
  transition: background-color 0.15s;
}

.apply-button:hover {
  background-color: rgb(12, 70, 196);
}

.save-button {
  background-color: white;
  color: rgb(12, 91, 196);
  border: 1px solid rgb(12, 91, 196);  
  cursor: pointer;
  font-weight: bold;
  font-size: 16px;
  border-radius: 25px;
  padding: 16px 40px;
  margin: 16px 10px;
}

.save-button:hover {
  background-color: rgba(12, 92, 196, 0.37);
  border: 2px solid;
}

I can't seem to make the border not move when I hover over it unless I use width & height.

**Comment by SuperSimpleDev** [comment]
Hm, maybe try offsetting the thicker border by decreasing your padding?
```css
.save-button:hover {
  background-color: rgba(12, 92, 196, 0.37);
  border: 2px solid;
  padding: 15px 39px;
}
```

**Comment by SuperSimpleDev** [comment]
Oops sorry I forgot to do that in the solutions. I'll update the solutions code.

**Comment by SuperSimpleDev** [comment]
@bringacupcake thanks for pointing this out!

**Comment by SuperSimpleDev** [comment]
Okay, I've also updated this in the sample solution code.
https://github.com/SuperSimpleDev/html-css-course-2022/blob/main/1-exercise-solutions/lesson-04/4e.html

**Comment by bringacupcake** [comment]
Thanks, I ended up troubleshooting the issue and working a lot on working with padding and margins when I hover and how to isolate the issue.

**Comment by ytarae** [comment]
I tried that with the updated code in the solution for the exercise, but despite that, the buttons still jump up a bit and I don't know what I'm doing wrong. I tried asking ChatGPT, but it didn't help. Are there any other solutions for those buttons? Thanks xx
