### ISSUE TITLE
8d,css and 8e.css  input 

### ISSUE THREAD

**Issue by kor1998** [SuperSimpleDev/html-css-course-2022#10]
when i am doing exercise in  8d and 8e in CSS why input is there in CSS and  is it a kind of CSS specificity like a p element can you explain in video pls so i may more understand about CSS

**Comment by SuperSimpleDev** [comment]
Good question. There's 2 steps:
1. I used input to style all <input> elements on the page.
2. Then, I styled some of the inputs individually using classes (some inputs are wider than others)
An element like `<input class="first-name">` will be target by `input { ... }` AND `.first-name { ... }` (in CSS multiple sets of styles can be combined together if they target the same element).

**Comment by SuperSimpleDev** [comment]
CSS specificity is different and is not used in these exercises. It's when they have the same property like:
```css
input {
  width: 300px;
}
.first-name {
  width: 500px;
}
```

**Comment by kor1998** [comment]
thank you but i want to know how its works can you record the 8d and 8e exercise in video so that i can understand well 
please do a video

**Comment by Ekimwaki1990** [comment]
Hi am doing exercise 13g .. How do u format a div to take the shape of another div in it`
