### ISSUE TITLE
3a and 4a do not resemble each other

### ISSUE THREAD

**Issue by magnir88** [SuperSimpleDev/html-css-course-2022#5]
padding solution for 4a doesn't resemble 
original 3a.

**Comment by SuperSimpleDev** [comment]
Hmm, that's weird. Can you share some screenshots or code?
Is it a little different or a lot different?

**Comment by magnir88** [comment]
![37C8E337-C3E9-4EDF-90E5-AF49A7C32965](https://user-images.githubusercontent.com/107348363/174432993-6d390772-1214-4712-9373-da26f908ccd2.jpeg)

**Comment by SuperSimpleDev** [comment]
Oh hmm, in the 3a exercise, line 6:
```css
  height: 40px
```
is missing a `;` at the end.

It should be:
```css
  height: 40px;
```
Can you try that? CSS needs a `;` (part of the syntax rules). Otherwise, the style won't work

**Comment by magnir88** [comment]
Oh I see! thank you!
