### ISSUE TITLE
Help me please (8d)

### ISSUE THREAD

**Issue by CindyTheCat** [SuperSimpleDev/html-css-course-2022#51]
I did everything correctly in 8d.html and 8d.css but every element was offset. I even tried copy+paste, and they still were offset. So I tried to make a new file and copy+paste everything the EXACTLY same and they weren't offset. I clicked inspect and the width of the "sign up" button should be 300px, but the file that was the same with GitHub seems to have a width of 266,4 pixels. I tried 266,4 pixels in my code and it worked. But the file that was the same as GitHub writes that the pixel of the button is 300px. Does anyone know why it changes the width automatically on that file and it doesn't on mine? Here is my code:
`<!DOCTYPE html>
<html>
  <head>

    <title>Lesson 08 Exercises</title>
    <style>

      .name-input, .email-input {
        display: block;
        margin-bottom: 5px;
      }

      .customer-support-message {
        width: 200px;
        display: inline-block;
        vertical-align: middle;
      }

      /* Unnecessary
      .survey-accept-button, .survey-deny-button {
        vertical-align: middle;
      }
      */

      .google-logo {
        width: 200px;
        margin-left: 150px;
        margin-bottom: 10px;
        display: block;
      }

      .exercise-e {
        width: 500px;
        border-color: rgb(200, 200, 200);
        border: none;
        border-radius: 250px;
        font-size: 16px;
        padding-top: 12px;
        padding-bottom: 12px;
        padding-left: 15px;
        padding-right: 15px;
        box-shadow: 0 1px 5px rgba(0, 0, 0, 0.25);
      }

      .first-name, .last-name, .email {
        border-width: 1px;
        border-style: solid;
        border-color: rgb(200, 200, 200);
        padding-top: 12px;
        padding-bottom: 12px;
        padding-left: 16px;
        padding-right: 16px;
        font-size: 16px;
        border-radius: 8px;
        margin-bottom: 12px;
      }

      .first-name {
        width: 148px;
      }

      .last-name {
        width: 148px;
      }

      .email {
        display: block;
        width: 300px;
      }

      .sign-up-button {
        background-color: rgb(47, 127, 231);
        color: white;
        border: none;
        width: 300px;
        padding-top: 14px;
        padding-bottom: 14px;
        font-size: 18px;
        font-weight: bold;
        border-radius: 8px;
      }

    </style>

  </head>
  <body>  

    <p>Exercise A</p>
    <input class="name-input" placeholder="Name">
    <input class="email-input" placeholder="Email">

    <p>Exercise B</p>
    <p class="customer-support-message">
      Thanks for chatting with our customer support. Would you like to take our quick survey?
    </p>
    <button class="survey-accept-button">Yes</button>
    <button class="survey-deny-button">No</button>

    <p>Exercise C</p>
    <img src="08-Images/google-logo.png" class="google-logo">
    <input placeholder="
    Search Google or type a URL
    " class="exercise-e" type="text">

    <p>Exercise D</p>
    <input class="first-name" type="text" placeholder="First name">
    <input class="last-name" type="text" placeholder="Last name">
    <input class="email" type="text" placeholder="Email">
    <button class="sign-up-button">Sign Up</button>
    

  </body>
</html>`

**Comment by CindyTheCat** [comment]
> 

Also the google logo png wont work, sorry

**Comment by CindyTheCat** [comment]
> I did everything correctly in 8d.html and 8d.css but every element was offset. I even tried copy+paste, and they still were offset. So I tried to make a new file and copy+paste everything the EXACTLY same and they weren't offset. I clicked inspect and the width of the "sign up" button should be 300px, but the file that was the same with GitHub seems to have a width of 266,4 pixels. I tried 266,4 pixels in my code and it worked. But the file that was the same as GitHub writes that the pixel of the button is 300px. Does anyone know why it changes the width automatically on that file and it doesn't on mine? Here is my code: `
> 
> ```
> <title>Lesson 08 Exercises</title>
> <style>
> 
>   .name-input, .email-input {
>     display: block;
>     margin-bottom: 5px;
>   }
> 
>   .customer-support-message {
>     width: 200px;
>     display: inline-block;
>     vertical-align: middle;
>   }
> 
>   /* Unnecessary
>   .survey-accept-button, .survey-deny-button {
>     vertical-align: middle;
>   }
>   */
> 
>   .google-logo {
>     width: 200px;
>     margin-left: 150px;
>     margin-bottom: 10px;
>     display: block;
>   }
> 
>   .exercise-e {
>     width: 500px;
>     border-color: rgb(200, 200, 200);
>     border: none;
>     border-radius: 250px;
>     font-size: 16px;
>     padding-top: 12px;
>     padding-bottom: 12px;
>     padding-left: 15px;
>     padding-right: 15px;
>     box-shadow: 0 1px 5px rgba(0, 0, 0, 0.25);
>   }
> 
>   .first-name, .last-name, .email {
>     border-width: 1px;
>     border-style: solid;
>     border-color: rgb(200, 200, 200);
>     padding-top: 12px;
>     padding-bottom: 12px;
>     padding-left: 16px;
>     padding-right: 16px;
>     font-size: 16px;
>     border-radius: 8px;
>     margin-bottom: 12px;
>   }
> 
>   .first-name {
>     width: 148px;
>   }
> 
>   .last-name {
>     width: 148px;
>   }
> 
>   .email {
>     display: block;
>     width: 300px;
>   }
> 
>   .sign-up-button {
>     background-color: rgb(47, 127, 231);
>     color: white;
>     border: none;
>     width: 300px;
>     padding-top: 14px;
>     padding-bottom: 14px;
>     font-size: 18px;
>     font-weight: bold;
>     border-radius: 8px;
>   }
> 
> </style>
> ```
> 
> ```
> <p>Exercise A</p>
> <input class="name-input" placeholder="Name">
> <input class="email-input" placeholder="Email">
> 
> <p>Exercise B</p>
> <p class="customer-support-message">
>   Thanks for chatting with our customer support. Would you like to take our quick survey?
> </p>
> <button class="survey-accept-button">Yes</button>
> <button class="survey-deny-button">No</button>
> 
> <p>Exercise C</p>
> <img src="08-Images/google-logo.png" class="google-logo">
> <input placeholder="
> Search Google or type a URL
> " class="exercise-e" type="text">
> 
> <p>Exercise D</p>
> <input class="first-name" type="text" placeholder="First name">
> <input class="last-name" type="text" placeholder="Last name">
> <input class="email" type="text" placeholder="Email">
> <button class="sign-up-button">Sign Up</button>
> ```
> 
> `
 Ok, I created a new file with the code I've pasted here and it works, I don't know why. Is there some corruption on my original file or something?

**Comment by CindyTheCat** [comment]
I've found the issue. whenever I type <!DOCTYPE html> at the start, it gets offset. I still don't know why can someone help me?

**Comment by StudioProgrammar** [comment]
Hmm I don't remember much about the lesson, but after copying the solution, I also ran into the same error. Well there's a pretty easy fix, increase the length of the email field to the total length of the two name fields. Then give that same width value to the button. I'll show my code for 8d down below:

Quick note: you may see a line where I styled all the elements at once. I did that just to snatch the styles I already made namely the border-radius and other stuff. But when things became different, I made another style section for the specific element to customize it further. Let me know if you have any questions! Also sorry about the unorganized html code, I don't know how to fix it here.

HTML:

`<input class="firstname-field" placeholder="First name" type="text">
<input class="lastname-field" placeholder="Last name" type="text">
<input class="email2-field" placeholder="Email" type="text">
<button class="signup-button">Sign Up</button>`

CSS:

`.firstname-field, .lastname-field, .email2-field, .signup-button {
    width: 120px;
    font-size: 16px;
    padding-top: 10px;
    padding-bottom: 10px;
    padding-left: 16px;
    padding-right: 16px;
    border-radius: 10px;
    border-width: 1px;
    border-color: rgb(200, 200, 200);
    border-style: solid;
}

.email2-field, .signup-button {
    width: 280px;
    display: block;
    margin-left: 25px;
    margin-top: 10px;
    margin-bottom: 10px;
}

.signup-button {
    background-color: rgb(47, 127, 231);
    color: white;
    width: 315px;
    margin-left: 25px;
    padding-top: 15px;
    padding-bottom: 15px;
    font-size: 17px;
    font-weight: bold;
    border: none;

}`

**Comment by CindyTheCat** [comment]
> Hmm I don't remember much about the lesson, but after copying the solution, I also ran into the same error. Well there's a pretty easy fix, increase the length of the email field to the total length of the two name fields. Then give that same width value to the button. I'll show my code for 8d down below:
> 
> Quick note: you may see a line where I styled all the elements at once. I did that just to snatch the styles I already made namely the border-radius and other stuff. But when things became different, I made another style section for the specific element to customize it further. Let me know if you have any questions! Also sorry about the unorganized html code, I don't know how to fix it here.
> 
> HTML:
> 
> `<input class="firstname-field" placeholder="First name" type="text"> <input class="lastname-field" placeholder="Last name" type="text"> <input class="email2-field" placeholder="Email" type="text"> <button class="signup-button">Sign Up</button>`
> 
> CSS:
> 
> `.firstname-field, .lastname-field, .email2-field, .signup-button { width: 120px; font-size: 16px; padding-top: 10px; padding-bottom: 10px; padding-left: 16px; padding-right: 16px; border-radius: 10px; border-width: 1px; border-color: rgb(200, 200, 200); border-style: solid; }
> 
> .email2-field, .signup-button { width: 280px; display: block; margin-left: 25px; margin-top: 10px; margin-bottom: 10px; }
> 
> .signup-button { background-color: rgb(47, 127, 231); color: white; width: 315px; margin-left: 25px; padding-top: 15px; padding-bottom: 15px; font-size: 17px; font-weight: bold; border: none;
> 
> }`

thank you so much, i though i was crazy but seeing someone else experience the same problem made it better. and i've changed my code <3
