### ISSUE TITLE
exercises 4h-4j

### ISSUE THREAD

**Issue by p3t3rw** [SuperSimpleDev/html-css-course-2022#63]
hi where can i find the web pages to inspect for exercises 4h-4j

**Comment by Fahad-Ali-8** [comment]
Bro Can you explain little more ?

**Comment by akshaycs435** [comment]
What ..?

**Comment by codeaj001** [comment]
> Bro Can you explain little more ?

What sir

**Comment by Fahad-Ali-8** [comment]
Nothing I was just trying to
help @p3t3rw.

**Comment by PaulHully** [comment]
> hi where can i find the web pages to inspect for exercises 4h-4j

I don't think there are any web pages to inspect for these exercises. I personally just tried to make them as close as possible without worrying too much about color accuracy or exact dimensions.
